export enum EE_PI {
  base_metals = "base_metals",
  condensates = "condensates",
  condensed_alloy = "condensed_alloy",
  construction_blocks = "construction_blocks",
  coolant = "coolant",
  crystal_compound = "crystal_compound",
  dark_compound = "dark_compound",
  fiber_composite = "fiber_composite",
  gleaming_alloy = "gleaming_alloy",
  glossy_compound = "glossy_compound",
  heavy_metals = "heavy_metals",
  heavy_water = "heavy_water",
  industrial_fibers = "industrial_fibers",
  ionic_solutions = "ionic_solutions",
  liquid_ozone = "liquid_ozone",
  lucent_compound = "lucent_compound",
  lustering_alloy = "lustering_alloy",
  motley_compound = "motley_compound",
  nanites = "nanites",
  noble_gas = "noble_gas",
  noble_metals = "noble_metals",
  opulent_compound = "opulent_compound",
  oxygen_isotopes = "oxygen_isotopes",
  plasmoids = "plasmoids",
  polyaramids = "polyaramids",
  precious_alloy = "precious_alloy",
  reactive_gas = "reactive_gas",
  reactive_metals = "reactive_metals",
  sheen_compound = "sheen_compound",
  silicate_glass = "silicate_glass",
  smartfab_units = "smartfab_units",
  supertensile_plastics = "supertensile_plastics",
  suspended_plasma = "suspended_plasma",
  toxic_metals = "toxic_metals",
}

export enum EE_PI_FUEL {
  heavy_water = "heavy_water",
  ionic_solutions = "ionic_solutions",
  liquid_ozone = "liquid_ozone",
  oxygen_isotopes = "oxygen_isotopes",
  plasmoids = "plasmoids",
  suspended_plasma = "suspended_plasma",
}

export enum EE_PI_SHIP {
  base_metals = "base_metals",
  condensed_alloy = "condensed_alloy",
  crystal_compound = "crystal_compound",
  dark_compound = "dark_compound",
  fiber_composite = "fiber_composite",
  gleaming_alloy = "gleaming_alloy",
  glossy_compound = "glossy_compound",
  heavy_metals = "heavy_metals",
  lucent_compound = "lucent_compound",
  lustering_alloy = "lustering_alloy",
  motley_compound = "motley_compound",
  noble_metals = "noble_metals",
  opulent_compound = "opulent_compound",
  precious_alloy = "precious_alloy",
  reactive_metals = "reactive_metals",
  sheen_compound = "sheen_compound",
  toxic_metals = "toxic_metals",
}

export enum EE_PI_STRUCT {
  condensates = "condensates",
  construction_blocks = "construction_blocks",
  coolant = "coolant",
  industrial_fibers = "industrial_fibers",
  nanites = "nanites",
  noble_gas = "noble_gas",
  polyaramids = "polyaramids",
  reactive_gas = "reactive_gas",
  silicate_glass = "silicate_glass",
  smartfab_units = "smartfab_units",
  supertensile_plastics = "supertensile_plastics",
}